export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PPRODUCTS = "RETRIEVE_PPRODUCTS";

export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
